# Workflow
# should have a  name
 name: hello
 
 # on tels when the workflow runs

 on:
   workflow_dispatch:
   
#jobs
# should be inside the workflow

jobs:
  say-hello:
  runs-on: ubunt-latest

# Steps
# Should be inside the job
  
  steps:
    -name: say hello to everyone 
     run: echo " Hi frnds"
     
# Actions
# Should be inside the Steps
